
// export const FETCH_DISCOVERY_DOCUMENT = 'FETCH_DISCOVERY_DOCUMENT';
// export const FETCH_BLANK_DISCOVERY_DOCUMENT = 'FETCH_BLANK_DISCOVERY_DOCUMENT';
// export const FETCH_DISCOVERY_DOCUMENT_PENDING = 'FETCH_DISCOVERY_DOCUMENT_PENDING';
// export const FETCH_DISCOVERY_DOCUMENT_FULFILLED = 'FETCH_DISCOVERY_DOCUMENT_FULFILLED';
// export const FETCH_DISCOVERY_DOCUMENT_REJECTED = 'FETCH_DISCOVERY_DOCUMENT_REJECTED';

export const FETCH_APPLICATIONS = 'FETCH_APPLICATIONS';
export const FETCH_APPLICATIONS_PENDING = 'FETCH_APPLICATIONS_PENDING';
export const FETCH_APPLICATIONS_FULFILLED = 'FETCH_APPLICATIONS_FULFILLED';
export const FETCH_APPLICATIONS_REJECTED = 'FETCH_APPLICATIONS_REJECTED';

export const FETCH_FACTS = 'FETCH_FACTS';
export const FETCH_FACTS_PENDING = 'FETCH_FACTS_PENDING';
export const FETCH_FACTS_FULFILLED = 'FETCH_FACTS_FULFILLED';
export const FETCH_FACTS_REJECTED = 'FETCH_FACTS_REJECTED';

export const FETCH_REPORTS = 'FETCH_REPORTS';
export const FETCH_REPORTS_PENDING = 'FETCH_REPORTS_PENDING';
export const FETCH_REPORTS_FULFILLED = 'FETCH_REPORTS_FULFILLED';
export const FETCH_REPORTS_REJECTED = 'FETCH_REPORTS_REJECTED';

export const FETCH_REPORT_METADATA = 'FETCH_REPORT_METADATA';
export const FETCH_REPORT_METADATA_PENDING = 'FETCH_REPORT_METADATA_PENDING';
export const FETCH_REPORT_METADATA_FULFILLED = 'FETCH_REPORT_METADATA_FULFILLED';
export const FETCH_REPORT_METADATA_REJECTED = 'FETCH_REPORT_METADATA_REJECTED';

export const SEARCH_REPORTS = 'SEARCH_REPORTS';
export const SEARCH_REPORTS_PENDING = 'SEARCH_REPORTS_PENDING';
export const SEARCH_REPORTS_FULFILLED = 'SEARCH_REPORTS_FULFILLED';
export const SEARCH_REPORTS_REJECTED = 'SEARCH_REPORTS_REJECTED';

export const FETCH_REPORT_SHEETS = 'FETCH_REPORT_SHEETS';
export const FETCH_FILTERED_REPORT_SHEETS = 'FETCH_FILTERED_REPORT_SHEETS';
export const FETCH_REPORT_SHEETS_PENDING = 'FETCH_REPORT_SHEETS_PENDING';
export const FETCH_REPORT_SHEETS_FULFILLED = 'FETCH_REPORT_SHEETS_FULFILLED';
export const FETCH_REPORT_SHEETS_REJECTED = 'FETCH_REPORT_SHEETS_REJECTED';

export const FETCH_REPORT_SHEET_DETAILS = 'FETCH_REPORT_SHEET_DETAILS';
export const FETCH_REPORT_SHEET_DETAILS_PENDING = 'FETCH_REPORT_SHEET_DETAILS_PENDING';
export const FETCH_REPORT_SHEET_DETAILS_FULFILLED = 'FETCH_REPORT_SHEET_DETAILS_FULFILLED';
export const FETCH_REPORT_SHEET_DETAILS_REJECTED = 'FETCH_REPORT_SHEET_DETAILS_REJECTED';

export const CHANGE_REPORT_SHEET_NAME = 'CHANGE_REPORT_SHEET_NAME';
export const CHANGE_REPORT_SHEET_DESC = 'CHANGE_REPORT_SHEET_DESC';

export const FETCH_DATASOURCE_LIST = 'FETCH_DATASOURCE_LIST';
export const FETCH_DATASOURCE_LIST_PENDING = 'FETCH_DATASOURCE_LIST_PENDING';
export const FETCH_DATASOURCE_LIST_FULFILLED = 'FETCH_DATASOURCE_LIST_FULFILLED';
export const FETCH_DATASOURCE_LIST_REJECTED = 'FETCH_DATASOURCE_LIST_REJECTED';

export const FETCH_SHEET_LIST = 'FETCH_SHEET_LIST';
export const FETCH_SHEET_LIST_PENDING = 'FETCH_SHEET_LIST_PENDING';
export const FETCH_SHEET_LIST_FULFILLED = 'FETCH_SHEET_LIST_FULFILLED';
export const FETCH_SHEET_LIST_REJECTED = 'FETCH_SHEET_LIST_REJECTED';

export const SAVE_DISCOVERY_DOCUMENT = 'SAVE_DISCOVERY_DOCUMENT';
export const SAVE_DISCOVERY_DOCUMENT_PENDING = 'SAVE_DISCOVERY_DOCUMENT_PENDING';
export const SAVE_DISCOVERY_DOCUMENT_FULFILLED = 'SAVE_DISCOVERY_DOCUMENT_FULFILLED';
export const SAVE_DISCOVERY_DOCUMENT_REJECTED = 'SAVE_DISCOVERY_DOCUMENT_REJECTED';

export const EDIT_DISCOVERY_DOCUMENT = 'EDIT_DISCOVERY_DOCUMENT';

export const FETCH_DIMENSION_LIST = 'FETCH_DIMENSION_LIST';
export const FETCH_DIMENSION_LIST_PENDING = 'FETCH_DIMENSION_LIST_PENDING';
export const FETCH_DIMENSION_LIST_FULFILLED = 'FETCH_DIMENSION_LIST_FULFILLED';
export const FETCH_DIMENSION_LIST_REJECTED = 'FETCH_DIMENSION_LIST_REJECTED';

export const FETCH_MEASURE_LIST = 'FETCH_MEASURE_LIST';
export const FETCH_MEASURE_LIST_PENDING = 'FETCH_MEASURE_LIST_PENDING';
export const FETCH_MEASURE_LIST_FULFILLED = 'FETCH_MEASURE_LIST_FULFILLED';
export const FETCH_MEASURE_LIST_REJECTED = 'FETCH_MEASURE_LIST_REJECTED';
export const SAVE_DIMENSION_FILTER = 'SAVE_DIMENSION_FILTER';
export const GET_FILTERS = 'GET_FILTERS';
export const SAVE_MEASURE_FILTER = 'SAVE_MEASURE_FILTER';

export const ADD_DATASOURCE = 'ADD_DATASOURCE';
export const REMOVE_DATASOURCE = 'REMOVE_DATASOURCE';

export const ADD_SHEET_TO_LIST = 'ADD_SHEET_TO_LIST';
export const UPDATE_SHEET_FROM_LIST = 'UPDATE_SHEET_FROM_LIST';
export const REMOVE_SHEET_FROM_LIST = 'REMOVE_SHEET_FROM_LIST';
export const DUPLICATE_SHEET_FROM_LIST = 'DUPLICATE_SHEET_FROM_LIST';
export const DISABLE_DATASOURCE = 'DISABLE_DATASOURCE';
export const ENABLE_DATASOURCE = 'ENABLE_DATASOURCE';
export const UPDATE_DRAWER_STATE = 'UPDATE_DRAWER_STATE';


export const SAVE_FONT_PROPERTIES = 'SAVE_FONT_PROPERTIES';
export const FETCH_SUMMARY = 'FETCH_SUMMARY';
export const FETCH_SUMMARY_PENDING = 'FETCH_SUMMARY_PENDING';
export const FETCH_SUMMARY_FULFILLED = 'FETCH_SUMMARY_FULFILLED';
export const FETCH_SUMMARY_REJECTED = 'FETCH_SUMMARY_REJECTED';
export const FETCH_COLUMN_ITEMS = 'FETCH_COLUMN_ITEMS';
export const FETCH_COLUMN_ITEMS_PENDING = 'FETCH_COLUMN_ITEMS_PENDING';
export const FETCH_COLUMN_ITEMS_FULFILLED = 'FETCH_COLUMN_ITEMS_FULFILLED';
export const FETCH_COLUMN_ITEMS_REJECTED = 'FETCH_COLUMN_ITEMS_REJECTED';
export const SAVE_DISPLAY_PROPERTIES = 'SAVE_DISPLAY_PROPERTIES';

export const CLEAR_APPLICATIONS = 'CLEAR_APPLICATIONS';
export const CLEAR_FACTS = 'CLEAR_FACTS';
export const CLEAR_REPORTS = 'CLEAR_REPORTS';
export const CLEAR_REPORT_SHEETS = 'CLEAR_REPORT_SHEETS';
export const CLEAR_FORM_DATA = 'CLEAR_FORM_DATA';


export const FETCH_DEFAULT_DATA_SHEET = 'FETCH_DEFAULT_DATA_SHEET';
export const FETCH_DEFAULT_DATA_SHEET_PENDING = 'FETCH_DEFAULT_DATA_SHEET_PENDING';
export const FETCH_DEFAULT_DATA_SHEET_FULFILLED = 'FETCH_DEFAULT_DATA_SHEET_FULFILLED';
export const FETCH_DEFAULT_DATA_SHEET_REJECTED = 'FETCH_DEFAULT_DATA_SHEET_REJECTED';
export const SHOW_PIVOT_LOADER = 'SHOW_PIVOT_LOADER';
export const HIDE_PIVOT_LOADER = 'HIDE_PIVOT_LOADER';

export const FETCH_CHART_CONFIG = 'FETCH_CHART_CONFIG';
export const FETCH_CHART_CONFIG_PENDING = 'FETCH_CHART_CONFIG_PENDING';
export const FETCH_CHART_CONFIG_FULFILLED = 'FETCH_CHART_CONFIG_FULFILLED';
export const FETCH_CHART_CONFIG_REJECTED = 'FETCH_CHART_CONFIG_REJECTED';

export const UPDATE_DATA_SHEET = 'UPDATE_DATA_SHEET';
export const UPDATE_DATA_SHEET_PENDING = 'UPDATE_DATA_SHEET_PENDING';
export const UPDATE_DATA_SHEET_FULFILLED = 'UPDATE_DATA_SHEET_FULFILLED';
export const UPDATE_DATA_SHEET_REJECTED = 'UPDATE_DATA_SHEET_REJECTED';

export const CHART_THIS_DIMENSION = 'CHART_THIS_DIMENSION';

export const UPDATE_ROW_COLUMN = 'UPDATE_ROW_COLUMN';
export const UPDATE_ROW_COLUMN_PENDING = 'UPDATE_ROW_COLUMN_PENDING';
export const UPDATE_ROW_COLUMN_FULFILLED = 'UPDATE_ROW_COLUMN_FULFILLED';
export const UPDATE_ROW_COLUMN_REJECTED = 'UPDATE_ROW_COLUMN_REJECTED';

export const UPDATE_SHEET_AXIS = 'UPDATE_SHEET_AXIS';

export const SAVE_MULTI_VIEW_SHEET_DATA = 'SAVE_MULTI_VIEW_SHEET_DATA';
export const SAVE_MULTI_VIEW_SHEET_DATA_PENDING = 'SAVE_MULTI_VIEW_SHEET_DATA_PENDING';
export const SAVE_MULTI_VIEW_SHEET_DATA_FULFILLED = 'SAVE_MULTI_VIEW_SHEET_DATA_FULFILLED';
export const SAVE_MULTI_VIEW_SHEET_DATA_REJECTED = 'SAVE_MULTI_VIEW_SHEET_DATA_REJECTED';

export const GET_MULTI_VIEW_SHEET_DATA = 'GET_MULTI_VIEW_SHEET_DATA';
export const GET_MULTI_VIEW_SHEET_DATA_PENDING = 'GET_MULTI_VIEW_SHEET_DATA_PENDING';
export const GET_MULTI_VIEW_SHEET_DATA_FULFILLED = 'GET_MULTI_VIEW_SHEET_DATA_FULFILLED';
export const GET_MULTI_VIEW_SHEET_DATA_REJECTED = 'GET_MULTI_VIEW_SHEET_DATA_REJECTED';
export const DROP_SHEET_ON_MULTI_VIEW = 'DROP_SHEET_ON_MULTI_VIEW';
export const TOGGLE_EDITABLE_MVS = 'TOGGLE_EDITABLE_MVS';
export const SET_EDITABLE_MVS = "SET_EDITABLE_MVS";

export const SAVE_MULTI_VIEW_SHEET_FILTER = 'SAVE_MULTI_VIEW_SHEET_FILTER';

export const FETCH_FILTERS_OF_MULTIVIEW_SHEET = 'FETCH_FILTERS_OF_MULTIVIEW_SHEET';
export const FETCH_FILTERS_OF_MULTIVIEW_SHEET_PENDING = 'FETCH_FILTERS_OF_MULTIVIEW_SHEET_PENDING';
export const FETCH_FILTERS_OF_MULTIVIEW_SHEET_FULFILLED = 'FETCH_FILTERS_OF_MULTIVIEW_SHEET_FULFILLED';
export const FETCH_FILTERS_OF_MULTIVIEW_SHEET_REJECTED = 'FETCH_FILTERS_OF_MULTIVIEW_SHEET_REJECTED';

export const FETCH_FILTERS_OF_DATA_SHEET = 'FETCH_FILTERS_OF_DATA_SHEET';
export const FETCH_FILTERS_OF_DATA_SHEET_PENDING = 'FETCH_FILTERS_OF_DATA_SHEET_PENDING';
export const FETCH_FILTERS_OF_DATA_SHEET_FULFILLED = 'FETCH_FILTERS_OF_DATA_SHEET_FULFILLED';
export const FETCH_FILTERS_OF_DATA_SHEET_REJECTED = 'FETCH_FILTERS_OF_DATA_SHEET_REJECTED';

export const FETCH_FILTERS_OF_DIMENSION = 'FETCH_FILTERS_OF_DIMENSION';
export const FETCH_FILTERS_OF_DIMENSION_PENDING = 'FETCH_FILTERS_OF_DIMENSION_PENDING';
export const FETCH_FILTERS_OF_DIMENSION_FULFILLED = 'FETCH_FILTERS_OF_DIMENSION_FULFILLED';
export const FETCH_FILTERS_OF_DIMENSION_REJECTED = 'FETCH_FILTERS_OF_DIMENSION_REJECTED';

export const UPDATE_FILTER = 'UPDATE_FILTER';

export const DELETE_FILTER = 'DELETE_FILTER';
export const DELETE_FILTER_PENDING = 'DELETE_FILTER_PENDING';
export const DELETE_FILTER_FULFILLED = 'DELETE_FILTER_FULFILLED';
export const DELETE_FILTER_REJECTED = 'DELETE_FILTER_REJECTED';

export const CHECK_UNCHECK_FILTER = 'CHECK_UNCHECK_FILTER';
export const CHECK_UNCHECK_FILTER_PENDING = 'CHECK_UNCHECK_FILTER_PENDING';
export const CHECK_UNCHECK_FILTER_FULFILLED = 'CHECK_UNCHECK_FILTER_FULFILLED';
export const CHECK_UNCHECK_FILTER_REJECTED = 'CHECK_UNCHECK_FILTER_REJECTED';

export const GET_DATAJOIN_FACTS = 'GET_DATAJOIN_FACTS';
export const GET_DATAJOIN_FACTS_PENDING = 'GET_DATAJOIN_FACTS_PENDING';
export const GET_DATAJOIN_FACTS_FULFILLED = 'GET_DATAJOIN_FACTS_FULFILLED';
export const GET_DATAJOIN_FACTS_REJECTED = 'GET_DATAJOIN_FACTS_REJECTED';


export const REMOVE_JOIN_TABLE_CONTENT = 'REMOVE_JOIN_TABLE_CONTENT';

export const LOAD_REPORT = 'LOAD_REPORT';
export const LOAD_REPORT_PENDING = 'LOAD_REPORT_PENDING';
export const LOAD_REPORT_FULFILLED = 'LOAD_REPORT_FULFILLED';
export const LOAD_REPORT_REJECTED = 'LOAD_REPORT_REJECTED';

// NEW MULTI VIEW SHEET ACTIONS
export const GET_MVS_DATA = 'GET_MVS_DATA';
export const GET_MVS_DATA_PENDING = 'GET_MVS_DATA_PENDING';
export const GET_MVS_DATA_FULFILLED = 'GET_MVS_DATA_FULFILLED';
export const GET_MVS_DATA_REJECTED = 'GET_MVS_DATA_REJECTED';

export const SAVE_DROPPED_SHEET = 'SAVE_DROPPED_SHEET';
export const REMOVE_DROPPED_SHEET = 'REMOVE_DROPPED_SHEET';
export const REMOVE_CHART_CONFIG = 'REMOVE_CHART_CONFIG';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const CHANGE_VISUALIZATION = 'CHANGE_VISUALIZATION';

export const GET_CHART_DATA = 'GET_CHART_DATA';
export const GET_CHART_DATA_PENDING = 'GET_CHART_DATA_PENDING';
export const GET_CHART_DATA_FULFILLED = 'GET_CHART_DATA_FULFILLED';
export const GET_CHART_DATA_REJECTED = 'GET_CHART_DATA_REJECTED';


export const FETCH_DIMENSION_FILTERS = 'FETCH_DIMENSION_FILTERS';
export const FETCH_DIMENSION_FILTERS_PENDING = 'FETCH_DIMENSION_FILTERS_PENDING';
export const FETCH_DIMENSION_FILTERS_FULFILLED = 'FETCH_DIMENSION_FILTERS_FULFILLED';
export const FETCH_DIMENSION_FILTERS_REJECTED = 'FETCH_DIMENSION_FILTERS_REJECTED';

export const GET_ALL_DIMENSION = 'GET_ALL_DIMENSION';
export const GET_ALL_DIMENSION_PENDING = 'GET_ALL_DIMENSION_PENDING';
export const GET_ALL_DIMENSION_FULFILLED = 'GET_ALL_DIMENSION_FULFILLED';
export const GET_ALL_DIMENSION_REJECTED = 'GET_ALL_DIMENSION_REJECTED';

export const GET_ALL_MEASURE = 'GET_ALL_MEASURE';
export const GET_ALL_MEASURE_PENDING = 'GET_ALL_MEASURE_PENDING';
export const GET_ALL_MEASURE_FULFILLED = 'GET_ALL_MEASURE_FULFILLED';
export const GET_ALL_MEASURE_REJECTED = 'GET_ALL_MEASURE_REJECTED';

export const CHECK_UNCHECK_ALL = 'CHECK_UNCHECK_ALL';
export const CHECK_UNCHECK_ITEM = 'CHECK_UNCHECK_ITEM';
export const GET_UPDATED_FILTER_LIST = 'GET_UPDATED_FILTER_LIST';
export const GET_SELECTED_FILTER_LIST = 'GET_SELECTED_FILTER_LIST';
export const CHECK_UNCHECK_FILTERS_FROM_MVS = 'CHECK_UNCHECK_FILTERS_FROM_MVS';
export const GET_SELECTED_FILTER_LIST_FROM_Modal = 'GET_SELECTED_FILTER_LIST_FROM_Modal';
export const ADD_USER_ENTERED_FILTER = 'ADD_USER_ENTERED_FILTER';
export const SAVE_FILTER_ON_MVS = 'SAVE_FILTER_ON_MVS';
export const UPDATE_FILTER_VIEW_ON_MVS = 'UPDATE_FILTER_VIEW_ON_MVS';
export const UPDATE_MVS_FILTER = 'UPDATE_MVS_FILTER';
export const UPDATE_MVS_DRAWER = 'UPDATE_MVS_DRAWER';
export const INIT_SHEET_LIST = 'INIT_SHEET_LIST';

export const APPLY_FILTER = 'APPLY_FILTER';
export const APPLY_FILTER_PENDING = 'APPLY_FILTER_PENDING';
export const APPLY_FILTER_FULFILLED = 'APPLY_FILTER_FULFILLED';
export const APPLY_FILTER_REJECTED = 'APPLY_FILTER_REJECTED';

export const SAVE_FILTER_FROM_CHART = 'SAVE_FILTER_FROM_CHART';
export const SAVE_FILTER_FROM_CHART_PENDING = 'SAVE_FILTER_FROM_CHART_PENDING';
export const SAVE_FILTER_FROM_CHART_FULFILLED = 'SAVE_FILTER_FROM_CHART_FULFILLED';
export const SAVE_FILTER_FROM_CHART_REJECTED = 'SAVE_FILTER_FROM_CHART_REJECTED';

export const FETCH_FILTERS_OF_MVS_SHEET = 'FETCH_FILTERS_OF_MVS_SHEET';
export const FETCH_FILTERS_OF_MVS_SHEET_PENDING = 'FETCH_FILTERS_OF_MVS_SHEET_PENDING';
export const FETCH_FILTERS_OF_MVS_SHEET_FULFILLED = 'FETCH_FILTERS_OF_MVS_SHEET_FULFILLED';
export const FETCH_FILTERS_OF_MVS_SHEET_REJECTED = 'FETCH_FILTERS_OF_MVS_SHEET_REJECTED';

export const GET_FILTER_LIST_FOR_MODAL = 'GET_FILTER_LIST_FOR_MODAL';
export const FETCH_MEASURE_FILTERS = 'FETCH_MEASURE_FILTERS';
export const UPDATE_SLIDER_VALUE = 'UPDATE_SLIDER_VALUE';

export const DELETE_FILTER_FROM_MVS = 'DELETE_FILTER_FROM_MVS';

export const APPLY_FILTER_MVS = 'APPLY_FILTER_MVS';
export const APPLY_FILTER_MVS_PENDING = 'APPLY_FILTER_MVS_PENDING';
export const APPLY_FILTER_MVS_FULFILLED = 'APPLY_FILTER_MVS_FULFILLED';
export const APPLY_FILTER_MVS_REJECTED = 'APPLY_FILTER_MVS_REJECTED';

export const CHECK_UNCHECK_FILTERS_FROM_MVS_Modal = 'CHECK_UNCHECK_FILTERS_FROM_MVS_Modal';
export const CHECK_UNCHECK_RADIO_FILTERS = 'CHECK_UNCHECK_RADIO_FILTERS';
export const CHECK_UNCHECK_DROPDOWN_FILTERS = 'CHECK_UNCHECK_DROPDOWN_FILTERS';

export const SHARE_DISCOVERY_DOCUMENT = 'SHARE_DISCOVERY_DOCUMENT';
export const SHARE_DISCOVERY_DOCUMENT_PENDING = 'SHARE_DISCOVERY_DOCUMENT_PENDING';
export const SHARE_DISCOVERY_DOCUMENT_FULFILLED = 'SHARE_DISCOVERY_DOCUMENT_FULFILLED';
export const SHARE_DISCOVERY_DOCUMENT_REJECTED = 'SHARE_DISCOVERY_DOCUMENT_REJECTED';

export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_LIST_PENDING = 'FETCH_USER_LIST_PENDING';
export const FETCH_USER_LIST_FULFILLED = 'FETCH_USER_LIST_FULFILLED';
export const FETCH_USER_LIST_REJECTED = 'FETCH_USER_LIST_REJECTED';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_SHARE_MODEL = 'TOGGLE_SHARE_MODEL';

export const SET_SIDEBAR = 'SET_SIDEBAR';

export const GET_OPTIONS_FOR_CUSTOM_ATTR = 'GET_OPTIONS_FOR_CUSTOM_ATTR';
export const GET_OPTIONS_FOR_CUSTOM_ATTR_PENDING = 'GET_OPTIONS_FOR_CUSTOM_ATTR_PENDING';
export const GET_OPTIONS_FOR_CUSTOM_ATTR_FULFILLED = 'GET_OPTIONS_FOR_CUSTOM_ATTR_FULFILLED';
export const GET_OPTIONS_FOR_CUSTOM_ATTR_REJECTED = 'GET_OPTIONS_FOR_CUSTOM_ATTR_REJECTED';

export const GET_ALL_MEASURES = 'GET_ALL_MEASURES';
export const GET_ALL_MEASURES_PENDING = 'GET_ALL_MEASURES_PENDING';
export const GET_ALL_MEASURES_FULFILLED = 'GET_ALL_MEASURES_FULFILLED';
export const GET_ALL_MEASURES_REJECTED = 'GET_ALL_MEASURES_REJECTED';

export const GET_ALL_DIMENSIONS = 'GET_ALL_DIMENSIONS';
export const GET_ALL_DIMENSIONS_PENDING = 'GET_ALL_DIMENSIONS_PENDING';
export const GET_ALL_DIMENSIONS_FULFILLED = 'GET_ALL_DIMENSIONS_FULFILLED';
export const GET_ALL_DIMENSIONS_REJECTED = 'GET_ALL_DIMENSIONS_REJECTED';
export const TOGGLE_EXPAND_COLLAPSE = 'TOGGLE_EXPAND_COLLAPSE';
export const SET_EXPAND_COLLAPSE = 'SET_EXPAND_COLLAPSE';

// ACTION FOR THE DATA_SOURCES & DATA_VIEWS
export const FETCH_DATA_VIEWS = 'FETCH_DATA_VIEWS';
export const FETCH_DATA_VIEWS_PENDING = 'FETCH_DATA_VIEWS_PENDING';
export const FETCH_DATA_VIEWS_FULFILLED = 'FETCH_DATA_VIEWS_FULFILLED';
export const FETCH_DATA_VIEWS_REJECTED = 'FETCH_DATA_VIEWS_REJECTED';

export const SEARCH_DATA_VIEWS = 'SEARCH_DATA_VIEWS';
export const SEARCH_DATA_VIEWS_PENDING = 'SEARCH_DATA_VIEWS_PENDING';
export const SEARCH_DATA_VIEWS_FULFILLED = 'SEARCH_DATA_VIEWS_FULFILLED';
export const SEARCH_DATA_VIEWS_REJECTED = 'SEARCH_DATA_VIEWS_REJECTED';

export const CLEAR_DATA_SOURCE_FORM_DATA = 'CLEAR_DATA_SOURCE_FORM_DATA';

export const SELECT_DATA_SOURCE_DETAILS = 'SELECT_DATA_SOURCE_DETAILS';
export const FETCH_DATA_SOURCE_PROPERTIES = 'FETCH_DATA_SOURCE_PROPERTIES';

export const FETCH_DATA_SOURCE_PROPERTIES_PENDING = 'FETCH_DATA_SOURCE_PROPERTIES_PENDING';
export const FETCH_DATA_SOURCE_PROPERTIES_FULFILLED = 'FETCH_DATA_SOURCE_PROPERTIES_FULFILLED';
export const FETCH_DATA_SOURCE_PROPERTIES_REJECTED = 'FETCH_DATA_SOURCE_PROPERTIES_REJECTED';

// export const FETCH_DATA_SOURCE_DETAILS = 'FETCH_DATA_SOURCE_DETAILS';
// export const FETCH_DATA_SOURCE_DETAILS_PENDING = 'FETCH_DATA_SOURCE_DETAILS_PENDING';
// export const FETCH_DATA_SOURCE_DETAILS_FULFILLED = 'FETCH_DATA_SOURCE_DETAILS_FULFILLED';
// export const FETCH_DATA_SOURCE_DETAILS_REJECTED = 'FETCH_DATA_SOURCE_DETAILS_REJECTED';
export const CHANGE_DATA_SOURCE_NAME_DESC = 'CHANGE_DATA_SOURCE_NAME_DESC';

//ACTIONS FOR THE DATA_VIEW
export const GET_DATA_VIEW_DATA = 'GET_DATA_VIEW_DATA';
export const GET_DATA_VIEW_DATA_PENDING = 'GET_DATA_VIEW_DATA_PENDING';
export const GET_DATA_VIEW_DATA_FULFILLED = 'GET_DATA_VIEW_DATA_FULFILLED';
export const GET_DATA_VIEW_DATA_REJECTED = 'GET_DATA_VIEW_DATA_REJECTED';

export const PUBLISH_DATA_MODEL = 'PUBLISH_DATA_MODEL';
export const PUBLISH_DATA_MODEL_PENDING = 'PUBLISH_DATA_MODEL_PENDING';
export const PUBLISH_DATA_MODEL_FULFILLED = 'PUBLISH_DATA_MODEL_FULFILLED';
export const PUBLISH_DATA_MODEL_REJECTED = 'PUBLISH_DATA_MODEL_REJECTED';

export const PUBLISH_AND_UPDATE_DATA_MODEL = 'PUBLISH_AND_UPDATE_DATA_MODEL';
export const PUBLISH_AND_UPDATE_DATA_MODEL_PENDING = 'PUBLISH_AND_UPDATE_DATA_MODEL_PENDING';
export const PUBLISH_AND_UPDATE_DATA_MODEL_FULFILLED = 'PUBLISH_AND_UPDATE_DATA_MODEL_FULFILLED';
export const PUBLISH_AND_UPDATE_DATA_MODEL_REJECTED = 'PUBLISH_AND_UPDATE_DATA_MODEL_REJECTED';

export const SET_FAV_DISCOVERY_DOCUMENT = 'SET_FAV_DISCOVERY_DOCUMENT';
export const SET_FAV_DISCOVERY_DOCUMENT_PENDING = 'SET_FAV_DISCOVERY_DOCUMENT_PENDING';
export const SET_FAV_DISCOVERY_DOCUMENT_FULFILLED = 'SET_FAV_DISCOVERY_DOCUMENT_FULFILLED';
export const SET_FAV_DISCOVERY_DOCUMENT_REJECTED = 'SET_FAV_DISCOVERY_DOCUMENT_REJECTED';

export const TOGGLE_SAVE_DISCOVERY_MODAL = 'TOGGLE_SAVE_DISCOVERY_MODAL';
export const TOGGLE_SAVE_AS_DISCOVERY_MODAL = 'TOGGLE_SAVE_AS_DISCOVERY_MODAL';

export const GET_OPT_LIST = 'GET_OPT_LIST';
export const GET_OPT_LIST_PENDING = 'GET_OPT_LIST_PENDING';
export const GET_OPT_LIST_FULFILLED = 'GET_OPT_LIST_FULFILLED';
export const GET_OPT_LIST_REJECTED = 'GET_OPT_LIST_REJECTED';

export const UPDATE_AXIS_VALUES = 'UPDATE_AXIS_VALUES';

// ACTION TO TOGGLE MODAL OF CUSTOM ATTRIBUTES
export const TOGGLE_CUSTOM_MEASURE_MODAL = 'TOGGLE_CUSTOM_MEASURE_MODAL';
export const TOGGLE_CUSTOM_ATTR_MODAL = 'TOGGLE_CUSTOM_ATTR_MODAL';

export const SET_FILTER_VISIBILITY = 'SET_FILTER_VISIBILITY';
export const TOGGLE_FILTER_VISIBILITY = 'TOGGLE_FILTER_VISIBILITY';
export const FILTER_COUNT_UPDATED = 'FILTER_COUNT_UPDATED';

export const SAVE_CUSTOM_MEASURE = 'SAVE_CUSTOM_MEASURE';
export const SAVE_CUSTOM_MEASURE_PENDING = 'SAVE_CUSTOM_MEASURE_PENDING';
export const SAVE_CUSTOM_MEASURE_FULFILLED = 'SAVE_CUSTOM_MEASURE_FULFILLED';
export const SAVE_CUSTOM_MEASURE_REJECTED = 'SAVE_CUSTOM_MEASURE_REJECTED';

export const SAVE_CUSTOM_DIMENSION = 'SAVE_CUSTOM_DIMENSION';
export const SAVE_CUSTOM_DIMENSION_PENDING = 'SAVE_CUSTOM_DIMENSION_PENDING';
export const SAVE_CUSTOM_DIMENSION_FULFILLED = 'SAVE_CUSTOM_DIMENSION_FULFILLED';
export const SAVE_CUSTOM_DIMENSION_REJECTED = 'SAVE_CUSTOM_DIMENSION_REJECTED';

export const DELETE_CUSTOM_ATTR = 'DELETE_CUSTOM_ATTR';
export const DELETE_CUSTOM_ATTR_PENDING = 'DELETE_CUSTOM_ATTR_PENDING';
export const DELETE_CUSTOM_ATTR_FULFILLED = 'DELETE_CUSTOM_ATTR_FULFILLED';
export const DELETE_CUSTOM_ATTR_REJECTED = 'DELETE_CUSTOM_ATTR_REJECTED';


export const GET_EXISTING_CUSTOM_ATTR = 'GET_EXISTING_CUSTOM_ATTR';
export const GET_EXISTING_CUSTOM_ATTR_PENDING = 'GET_EXISTING_CUSTOM_ATTR_PENDING';
export const GET_EXISTING_CUSTOM_ATTR_FULFILLED = 'GET_EXISTING_CUSTOM_ATTR_FULFILLED';
export const GET_EXISTING_CUSTOM_ATTR_REJECTED = 'GET_EXISTING_CUSTOM_ATTR_REJECTED';

export const GET_EXISTING_CUSTOM_MEASURE = 'GET_EXISTING_CUSTOM_MEASURE';
export const GET_EXISTING_CUSTOM_MEASURE_PENDING = 'GET_EXISTING_CUSTOM_MEASURE_PENDING';
export const GET_EXISTING_CUSTOM_MEASURE_FULFILLED = 'GET_EXISTING_CUSTOM_MEASURE_FULFILLED';
export const GET_EXISTING_CUSTOM_MEASURE_REJECTED = 'GET_EXISTING_CUSTOM_MEASURE_REJECTED';


export const SAVE_CUSTOM_DM_LIST = 'SAVE_CUSTOM_DM_LIST';
export const SAVE_CUSTOM_DM_LIST_PENDING = 'SAVE_CUSTOM_DM_LIST_PENDING';
export const SAVE_CUSTOM_DM_LIST_FULFILLED = 'SAVE_CUSTOM_DM_LIST_FULFILLED';
export const SAVE_CUSTOM_DM_LIST_REJECTED = 'SAVE_CUSTOM_DM_LIST_REJECTED';

export const UPDATE_SUMMERIES_AT_COLUMN_LEVEL = 'UPDATE_SUMMERIES_AT_COLUMN_LEVEL';
export const GET_SUMMERIES_AT_COLUMN_LEVEL = 'GET_SUMMERIES_AT_COLUMN_LEVEL';

//Constant for Contextual Menu Ranges
export const TOGGLE_RANGES_FORM = 'TOGGLE_RANGES_FORM';
export const SAVE_RANGES_FORM = 'SAVE_RANGES_FORM';

export const UPDATE_CHART = "UPDATE_CHART";
export const UPDATE_CHART_ATTRIBUTES = 'UPDATE_CHART_ATTRIBUTES';

export const SAVE_AS_PUBLISH = 'SAVE_AS_PUBLISH';
export const SAVE_AS_PUBLISH_PENDING = 'SAVE_AS_PUBLISH_PENDING';
export const SAVE_AS_PUBLISH_FULFILLED = 'SAVE_AS_PUBLISH_FULFILLED';
export const SAVE_AS_PUBLISH_REJECTED = 'SAVE_AS_PUBLISH_REJECTED';

export const SAVE_AS_DOCUMENT = 'SAVE_AS_DOCUMENT';
export const SAVE_AS_DOCUMENT_PENDING = 'SAVE_AS_DOCUMENT_PENDING';
export const SAVE_AS_DOCUMENT_FULFILLED = 'SAVE_AS_DOCUMENT_FULFILLED';
export const SAVE_AS_DOCUMENT_REJECTED = 'SAVE_AS_DOCUMENT_REJECTED';

export const GET_LIST_OF_CUSTOM_DM = 'GET_LIST_OF_CUSTOM_DM';
export const GET_LIST_OF_CUSTOM_DM_PENDING = 'GET_LIST_OF_CUSTOM_DM_PENDING';
export const GET_LIST_OF_CUSTOM_DM_FULFILLED = 'GET_LIST_OF_CUSTOM_DM_FULFILLED';
export const GET_LIST_OF_CUSTOM_DM_REJECTED = 'GET_LIST_OF_CUSTOM_DM_REJECTED';