export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_LIST_PENDING = 'FETCH_USER_LIST_PENDING';
export const FETCH_USER_LIST_FULFILLED = 'FETCH_USER_LIST_FULFILLED';
export const FETCH_USER_LIST_REJECTED = 'FETCH_USER_LIST_REJECTED';

export const TOGGLE_SHARE_MODEL = 'TOGGLE_SHARE_MODEL';

export const SHARE_DISCOVERY_DOCUMENT = 'SHARE_DISCOVERY_DOCUMENT';
export const SHARE_DISCOVERY_DOCUMENT_PENDING = 'SHARE_DISCOVERY_DOCUMENT_PENDING';
export const SHARE_DISCOVERY_DOCUMENT_FULFILLED = 'SHARE_DISCOVERY_DOCUMENT_FULFILLED';
export const SHARE_DISCOVERY_DOCUMENT_REJECTED = 'SHARE_DISCOVERY_DOCUMENT_REJECTED';

export const SAVE_DISCOVERY_DOCUMENT = 'SAVE_DISCOVERY_DOCUMENT';
export const SAVE_DISCOVERY_DOCUMENT_PENDING = 'SAVE_DISCOVERY_DOCUMENT_PENDING';
export const SAVE_DISCOVERY_DOCUMENT_FULFILLED = 'SAVE_DISCOVERY_DOCUMENT_FULFILLED';
export const SAVE_DISCOVERY_DOCUMENT_REJECTED = 'SAVE_DISCOVERY_DOCUMENT_REJECTED';

export const EDIT_DISCOVERY_DOCUMENT = 'EDIT_DISCOVERY_DOCUMENT';

export const TOGGLE_SAVE_DISCOVERY_MODAL = 'TOGGLE_SAVE_DISCOVERY_MODAL';
export const TOGGLE_SAVE_AS_DISCOVERY_MODAL = 'TOGGLE_SAVE_AS_DISCOVERY_MODAL';

export const SET_FAV_DISCOVERY_DOCUMENT = 'SET_FAV_DISCOVERY_DOCUMENT';
export const SET_FAV_DISCOVERY_DOCUMENT_PENDING = 'SET_FAV_DISCOVERY_DOCUMENT_PENDING';
export const SET_FAV_DISCOVERY_DOCUMENT_FULFILLED = 'SET_FAV_DISCOVERY_DOCUMENT_FULFILLED';
export const SET_FAV_DISCOVERY_DOCUMENT_REJECTED = 'SET_FAV_DISCOVERY_DOCUMENT_REJECTED';

export const SAVE_AS_PUBLISH = 'SAVE_AS_PUBLISH';
export const SAVE_AS_PUBLISH_PENDING = 'SAVE_AS_PUBLISH_PENDING';
export const SAVE_AS_PUBLISH_FULFILLED = 'SAVE_AS_PUBLISH_FULFILLED';
export const SAVE_AS_PUBLISH_REJECTED = 'SAVE_AS_PUBLISH_REJECTED';

export const GET_LIST_OF_CUSTOM_DM = 'GET_LIST_OF_CUSTOM_DM';
export const GET_LIST_OF_CUSTOM_DM_PENDING = 'GET_LIST_OF_CUSTOM_DM_PENDING';
export const GET_LIST_OF_CUSTOM_DM_FULFILLED = 'GET_LIST_OF_CUSTOM_DM_FULFILLED';
export const GET_LIST_OF_CUSTOM_DM_REJECTED = 'GET_LIST_OF_CUSTOM_DM_REJECTED';

export const SAVE_CUSTOM_DM_LIST = 'SAVE_CUSTOM_DM_LIST';
export const SAVE_CUSTOM_DM_LIST_PENDING = 'SAVE_CUSTOM_DM_LIST_PENDING';
export const SAVE_CUSTOM_DM_LIST_FULFILLED = 'SAVE_CUSTOM_DM_LIST_FULFILLED';
export const SAVE_CUSTOM_DM_LIST_REJECTED = 'SAVE_CUSTOM_DM_LIST_REJECTED';

export const SAVE_AS_DOCUMENT = 'SAVE_AS_DOCUMENT';
export const SAVE_AS_DOCUMENT_PENDING = 'SAVE_AS_DOCUMENT_PENDING';
export const SAVE_AS_DOCUMENT_FULFILLED = 'SAVE_AS_DOCUMENT_FULFILLED';
export const SAVE_AS_DOCUMENT_REJECTED = 'SAVE_AS_DOCUMENT_REJECTED';