export const ADD_DATASOURCE = 'ADD_DATASOURCE';
export const REMOVE_DATASOURCE = 'REMOVE_DATASOURCE';

export const FETCH_DATASOURCE_LIST = 'FETCH_DATASOURCE_LIST';
export const FETCH_DATASOURCE_LIST_PENDING = 'FETCH_DATASOURCE_LIST_PENDING';
export const FETCH_DATASOURCE_LIST_FULFILLED = 'FETCH_DATASOURCE_LIST_FULFILLED';
export const FETCH_DATASOURCE_LIST_REJECTED = 'FETCH_DATASOURCE_LIST_REJECTED';

export const DISABLE_DATASOURCE = 'DISABLE_DATASOURCE';
export const ENABLE_DATASOURCE = 'ENABLE_DATASOURCE';

export const GET_DATAJOIN_FACTS = 'GET_DATAJOIN_FACTS';
export const GET_DATAJOIN_FACTS_PENDING = 'GET_DATAJOIN_FACTS_PENDING';
export const GET_DATAJOIN_FACTS_FULFILLED = 'GET_DATAJOIN_FACTS_FULFILLED';
export const GET_DATAJOIN_FACTS_REJECTED = 'GET_DATAJOIN_FACTS_REJECTED';

//ACTIONS FOR THE DATA_VIEW
export const GET_DATA_VIEW_DATA = 'GET_DATA_VIEW_DATA';
export const GET_DATA_VIEW_DATA_PENDING = 'GET_DATA_VIEW_DATA_PENDING';
export const GET_DATA_VIEW_DATA_FULFILLED = 'GET_DATA_VIEW_DATA_FULFILLED';
export const GET_DATA_VIEW_DATA_REJECTED = 'GET_DATA_VIEW_DATA_REJECTED';

export const PUBLISH_DATA_MODEL = 'PUBLISH_DATA_MODEL';
export const PUBLISH_DATA_MODEL_PENDING = 'PUBLISH_DATA_MODEL_PENDING';
export const PUBLISH_DATA_MODEL_FULFILLED = 'PUBLISH_DATA_MODEL_FULFILLED';
export const PUBLISH_DATA_MODEL_REJECTED = 'PUBLISH_DATA_MODEL_REJECTED';

export const PUBLISH_AND_UPDATE_DATA_MODEL = 'PUBLISH_AND_UPDATE_DATA_MODEL';
export const PUBLISH_AND_UPDATE_DATA_MODEL_PENDING = 'PUBLISH_AND_UPDATE_DATA_MODEL_PENDING';
export const PUBLISH_AND_UPDATE_DATA_MODEL_FULFILLED = 'PUBLISH_AND_UPDATE_DATA_MODEL_FULFILLED';
export const PUBLISH_AND_UPDATE_DATA_MODEL_REJECTED = 'PUBLISH_AND_UPDATE_DATA_MODEL_REJECTED';

export const REMOVE_JOIN_TABLE_CONTENT = 'REMOVE_JOIN_TABLE_CONTENT';


export const LOAD_REPORT = 'LOAD_REPORT';
export const LOAD_REPORT_PENDING = 'LOAD_REPORT_PENDING';
export const LOAD_REPORT_FULFILLED = 'LOAD_REPORT_FULFILLED';
export const LOAD_REPORT_REJECTED = 'LOAD_REPORT_REJECTED';

export const UPDATE_DRAWER_STATE = 'UPDATE_DRAWER_STATE';